"""Baseline PostgreSQL — esquemas + tablas ORM (create_all) + star-schema cat/stg.

Edición PostgreSQL. Crea todo el esquema desde cero para Postgres:
  1. CREATE SCHEMA de los 9 esquemas.
  2. Base.metadata.create_all() → tablas ORM (Config/DW/ETL/Audit/Security/exam/Visita).
  3. DDL explícito del star-schema cat.* y staging stg.* (traducido de T-SQL:
     NVARCHAR→VARCHAR, IDENTITY→GENERATED BY DEFAULT AS IDENTITY, BIT→BOOLEAN,
     DATETIME/DATETIME2→TIMESTAMPTZ, TINYINT→SMALLINT, DECIMAL→NUMERIC).

Revision ID: 0001_baseline_postgres
Revises:
Create Date: 2026-07-04
"""
from alembic import op

revision = "0001_baseline_postgres"
down_revision = None
branch_labels = None
depends_on = None

_SCHEMAS = ["Config", "DW", "ETL", "Audit", "Security", "exam", "Visita", "cat", "stg"]

# DDL del star-schema cat.* + stg.* (identificadores mixtos entrecomillados para que
# el SQL crudo de categorizacion_service/cobertura_predictiva_service los matchee).
_CAT_STG_DDL = [
    '''CREATE TABLE "cat"."DimPais" (
        "PaisKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisIdOrigen" INTEGER, "CodigoPais" CHAR(2) NOT NULL,
        "NombrePais" VARCHAR(100) NOT NULL, "Moneda" CHAR(3), "ZonaHoraria" VARCHAR(80),
        "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."DimEspecialidad" (
        "EspecialidadKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Especialidad" VARCHAR(150) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimCentroMedico" (
        "CentroMedicoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CentroMedico" VARCHAR(200) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimGeografia" (
        "GeografiaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Provincia" VARCHAR(120) NOT NULL,
        "Municipio" VARCHAR(120) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimEquipo" (
        "EquipoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CodigoEquipo" VARCHAR(30) NOT NULL,
        "NombreEquipo" VARCHAR(120) NOT NULL, "Descripcion" VARCHAR(250), "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimMedico" (
        "MedicoKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CodigoMedico" VARCHAR(50), "NombreMedico" VARCHAR(200) NOT NULL,
        "EspecialidadKey" INTEGER, "Activo" BOOLEAN NOT NULL, "MedicoId" INTEGER )''',
    '''CREATE TABLE "cat"."DimRepresentanteMedico" (
        "RepresentanteKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "RepresentanteIdOrigen" INTEGER,
        "CodigoRepresentante" VARCHAR(30) NOT NULL, "NombreRepresentante" VARCHAR(150) NOT NULL,
        "LineaIdOrigen" INTEGER, "GerenteIdOrigen" INTEGER, "Email" VARCHAR(150), "Zona" VARCHAR(80),
        "FechaIngreso" DATE, "Cedula" VARCHAR(30), "CodigoOrigenExcel" VARCHAR(50),
        "EquipoTexto" VARCHAR(120), "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimComponenteCategoria" (
        "ComponenteKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "CodigoComponente" VARCHAR(50) NOT NULL, "NombreComponente" VARCHAR(150) NOT NULL,
        "TipoEvaluacion" VARCHAR(30) NOT NULL, "PesoComponentePct" NUMERIC(9,6) NOT NULL,
        "Requerido" BOOLEAN NOT NULL, "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."DimReglaCategoriaMedica" (
        "ReglaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "ComponenteKey" INTEGER NOT NULL, "CodigoRegla" VARCHAR(80) NOT NULL,
        "Detalle" VARCHAR(200) NOT NULL, "ValorMinimo" NUMERIC(18,4), "ValorMaximo" NUMERIC(18,4),
        "ValorTexto" VARCHAR(200), "Criterio" SMALLINT NOT NULL, "PesoComponentePct" NUMERIC(9,6) NOT NULL,
        "PuntajePct" NUMERIC(9,6) NOT NULL, "VigenteDesde" DATE NOT NULL, "VigenteHasta" DATE,
        "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."DimClasificacionMedica" (
        "ClasificacionKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Clase" CHAR(1) NOT NULL, "PuntajeMinPct" NUMERIC(9,6) NOT NULL,
        "PuntajeMaxPct" NUMERIC(9,6) NOT NULL, "OrdenClase" SMALLINT NOT NULL, "VigenteDesde" DATE NOT NULL,
        "VigenteHasta" DATE, "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."DimCiclo" (
        "CicloKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CodigoCiclo" VARCHAR(20) NOT NULL, "LineaId" INTEGER, "Linea" VARCHAR(100),
        "FechaInicio" DATE NOT NULL, "FechaFin" DATE NOT NULL, "DiasHabilesCiclo" INTEGER,
        "MetaCoberturaPct" NUMERIC(5,4) NOT NULL, "MetaContactosCiclo" INTEGER, "CicloNumeroAnual" INTEGER,
        "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."DimCalendario" (
        "FechaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Fecha" DATE NOT NULL, "CicloKey" INTEGER, "EsHabil" BOOLEAN NOT NULL,
        "EsFeriado" BOOLEAN NOT NULL, "Semana" INTEGER, "Mes" INTEGER, "Anio" INTEGER, "Nota" VARCHAR(200),
        "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."FactTargetMedicoCiclo" (
        "TargetMedicoKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "CicloKey" INTEGER NOT NULL, "PaisKey" INTEGER NOT NULL, "RepresentanteKey" INTEGER NOT NULL,
        "MedicoKey" BIGINT, "CodigoMedicoOrigen" VARCHAR(50) NOT NULL, "NombreMedico" VARCHAR(200),
        "EspecialidadKey" INTEGER, "Potencial" VARCHAR(5), "Territorio" VARCHAR(100), "FrecuenciaObjetivo" INTEGER,
        "ProgramadoFlag" BOOLEAN NOT NULL, "CategoriaMedica" VARCHAR(5), "Fuente" VARCHAR(100),
        "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."FactVisitaMedica" (
        "VisitaKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "VisitaIdOrigen" VARCHAR(50), "FechaVisita" DATE NOT NULL, "CicloKey" INTEGER NOT NULL,
        "PaisKey" INTEGER NOT NULL, "RepresentanteKey" INTEGER NOT NULL, "CodigoMedicoOrigen" VARCHAR(50) NOT NULL,
        "MedicoKey" BIGINT, "TipoContacto" VARCHAR(50), "EstadoVisita" VARCHAR(50) NOT NULL,
        "ProductoFoco" VARCHAR(100), "Fuente" VARCHAR(100), "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."LoadBatch" (
        "LoadBatchKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ArchivoOrigen" VARCHAR(260) NOT NULL, "Periodo" VARCHAR(20) NOT NULL, "CodigoPaisDefault" CHAR(2),
        "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now(), "UsuarioCarga" VARCHAR(150),
        "Estado" VARCHAR(20) NOT NULL, "Mensaje" VARCHAR(1000) )''',
    '''CREATE TABLE "cat"."FactMedicoCategoriaSnapshot" (
        "MedicoCategoriaKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "LoadBatchKey" BIGINT NOT NULL, "RowNumber" INTEGER NOT NULL, "Periodo" VARCHAR(20),
        "PaisKey" INTEGER NOT NULL, "MedicoKey" BIGINT NOT NULL, "CentroMedicoKey" INTEGER, "GeografiaKey" INTEGER,
        "RepresentanteKey" INTEGER, "Equipo" VARCHAR(120), "LineaIdOrigen" INTEGER,
        "PacientesSemana" NUMERIC(18,4), "CostoConsulta" NUMERIC(18,4), "RecetasSemana" VARCHAR(80),
        "UbicacionTerritorialCM" VARCHAR(80), "KOL" VARCHAR(150), "PuntajeTotalPct" NUMERIC(9,6),
        "ClasificacionKey" INTEGER, "CategoriaCalculada" CHAR(1), "CategoriaExcel" VARCHAR(20),
        "EstadoCalculo" VARCHAR(20) NOT NULL, "MensajeCalculo" VARCHAR(500),
        "FechaCalculoUtc" TIMESTAMPTZ NOT NULL DEFAULT now(), "Provincia" VARCHAR(120), "Municipio" VARCHAR(120),
        "EstadoConciliacion" VARCHAR(30) )''',
    '''CREATE TABLE "cat"."FactMedicoCategoriaDetalle" (
        "MedicoCategoriaDetalleKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "MedicoCategoriaKey" BIGINT NOT NULL, "ComponenteKey" INTEGER NOT NULL, "ReglaKey" INTEGER,
        "ValorEntradaTexto" VARCHAR(200), "ValorEntradaNumero" NUMERIC(18,4), "Criterio" SMALLINT,
        "PuntajePct" NUMERIC(9,6), "EstadoComponente" VARCHAR(20) NOT NULL )''',
    '''CREATE TABLE "cat"."KpiCoberturaPredictiva" (
        "KpiKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "FechaCorte" DATE NOT NULL, "CicloKey" INTEGER NOT NULL, "PaisKey" INTEGER NOT NULL, "Linea" VARCHAR(100),
        "GD" VARCHAR(150), "RepresentanteKey" INTEGER NOT NULL, "NombreVM" VARCHAR(150),
        "MedicosProgramados" INTEGER NOT NULL, "MedicosVisitadosUnicos" INTEGER NOT NULL,
        "CoberturaActualPct" NUMERIC(9,6) NOT NULL, "CoberturaEsperadaPct" NUMERIC(9,6) NOT NULL,
        "CoberturaProyectadaPct" NUMERIC(9,6) NOT NULL, "MetaCoberturaPct" NUMERIC(9,6) NOT NULL,
        "BrechaActualVsEsperada" NUMERIC(9,6) NOT NULL, "BrechaProyectadaVsMeta" NUMERIC(9,6) NOT NULL,
        "MedicosRequeridosMeta" INTEGER NOT NULL, "MedicosPendientesMeta" INTEGER NOT NULL,
        "MedicosDiariosRequeridos" INTEGER NOT NULL, "ContactosMetaCiclo" INTEGER NOT NULL,
        "ContactosRealizados" INTEGER NOT NULL, "CumplimientoContactosPct" NUMERIC(9,6) NOT NULL,
        "ContactosProyectados" NUMERIC(12,4) NOT NULL, "ContactosPendientes" NUMERIC(12,4) NOT NULL,
        "ContactosDiariosRequeridos" INTEGER NOT NULL, "DiasHabilesTotales" INTEGER NOT NULL,
        "DiasHabilesTranscurridos" INTEGER NOT NULL, "DiasHabilesRestantes" INTEGER NOT NULL,
        "EstadoCobertura" VARCHAR(10) NOT NULL, "EstadoRitmo" VARCHAR(10) NOT NULL, "EstadoPSP" VARCHAR(10) NOT NULL,
        "LecturaAccionable" VARCHAR(2000), "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "stg"."MedicoCategoriaInput" (
        "LoadBatchKey" BIGINT NOT NULL, "RowNumber" INTEGER NOT NULL, "CodigoPais" CHAR(2) NOT NULL,
        "Periodo" VARCHAR(20), "Equipo" VARCHAR(120), "LineaIdOrigen" INTEGER, "CodigoRepresentante" VARCHAR(30),
        "NombreRepresentante" VARCHAR(150), "Medico" VARCHAR(200) NOT NULL, "CentroMedico" VARCHAR(200),
        "Especialidad" VARCHAR(150), "Provincia" VARCHAR(120), "Municipio" VARCHAR(120),
        "PacientesSemana" NUMERIC(18,4), "CostoConsulta" NUMERIC(18,4), "RecetasSemana" VARCHAR(80),
        "UbicacionTerritorialCM" VARCHAR(80), "KOL" VARCHAR(150), "CategoriaExcel" VARCHAR(20),
        "Activo" BOOLEAN NOT NULL, PRIMARY KEY ("LoadBatchKey", "RowNumber") )''',
]


def upgrade():
    bind = op.get_bind()
    for s in _SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{s}"')
    # Tablas ORM (Config/DW/ETL/Audit/Security/exam/Visita) desde los modelos.
    import app.models.usuario  # noqa: F401
    import app.models.dimensiones  # noqa: F401
    import app.models.hechos  # noqa: F401
    import app.models.visita  # noqa: F401
    import app.models.exam_models  # noqa: F401
    from app.db.database import Base
    Base.metadata.create_all(bind=bind)
    # Star-schema cat.* + staging stg.*
    for ddl in _CAT_STG_DDL:
        op.execute(ddl)


def downgrade():
    for ddl in _CAT_STG_DDL:
        # nombre de tabla entre las primeras comillas
        import re
        m = re.search(r'CREATE TABLE (".+?"\.".+?")', ddl)
        if m:
            op.execute(f'DROP TABLE IF EXISTS {m.group(1)} CASCADE')
    from app.db.database import Base
    Base.metadata.drop_all(bind=op.get_bind())
    for s in reversed(_SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{s}" CASCADE')
