"""Baseline PostgreSQL — esquemas + foto congelada del DDL + star-schema cat/stg.

Edición PostgreSQL. Crea el esquema desde cero para Postgres:
  1. CREATE SCHEMA de los 9 esquemas.
  2. DDL de las 85 tablas que existían el 2026-07-04, leído de la FOTO CONGELADA
     `0001_baseline_postgres.sql` (mismo directorio).
  3. DDL explícito de las 6 tablas cat.*/stg.* que NO tienen modelo ORM.

POR QUÉ UNA FOTO Y NO `Base.metadata.create_all()` (que es lo que hacía antes):
`env.py` importa TODOS los módulos de modelos, porque autogenerate lo necesita.
Por eso `create_all()` aquí no creaba el esquema de julio: creaba el de HOY.
Cada modelo nuevo del proyecto se colaba retroactivamente dentro del baseline
—144 tablas en vez de 85— y luego chocaba con la migración posterior que de
verdad lo crea. En una base ya instalada no se nota, porque 0001 no se vuelve a
correr; se manifiesta solo al instalar desde cero, que es exactamente lo que se
hace en el servidor de un cliente. La foto no depende de los modelos, así que
ningún cambio futuro del ORM puede volver a alterar el pasado.

Revision ID: 0001_baseline_postgres
Revises:
Create Date: 2026-07-04
"""
from pathlib import Path

from alembic import op

revision = "0001_baseline_postgres"
down_revision = None
branch_labels = None
depends_on = None

_SCHEMAS = ["Config", "DW", "ETL", "Audit", "Security", "exam", "Visita", "cat", "stg"]

# Solo las 6 tablas cat.*/stg.* SIN modelo ORM (las otras 13 las crea create_all).
_CAT_STG_DDL = [
    '''CREATE TABLE "cat"."DimCentroMedico" (
        "CentroMedicoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CentroMedico" VARCHAR(200) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimGeografia" (
        "GeografiaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Provincia" VARCHAR(120) NOT NULL,
        "Municipio" VARCHAR(120) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimEquipo" (
        "EquipoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CodigoEquipo" VARCHAR(30) NOT NULL,
        "NombreEquipo" VARCHAR(120) NOT NULL, "Descripcion" VARCHAR(250), "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimReglaCategoriaMedica" (
        "ReglaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "ComponenteKey" INTEGER NOT NULL, "CodigoRegla" VARCHAR(80) NOT NULL,
        "Detalle" VARCHAR(200) NOT NULL, "ValorMinimo" NUMERIC(18,4), "ValorMaximo" NUMERIC(18,4),
        "ValorTexto" VARCHAR(200), "Criterio" SMALLINT NOT NULL, "PesoComponentePct" NUMERIC(9,6) NOT NULL,
        "PuntajePct" NUMERIC(9,6) NOT NULL, "VigenteDesde" DATE NOT NULL, "VigenteHasta" DATE,
        "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."FactMedicoCategoriaDetalle" (
        "MedicoCategoriaDetalleKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "MedicoCategoriaKey" BIGINT NOT NULL, "ComponenteKey" INTEGER NOT NULL, "ReglaKey" INTEGER,
        "ValorEntradaTexto" VARCHAR(200), "ValorEntradaNumero" NUMERIC(18,4), "Criterio" SMALLINT,
        "PuntajePct" NUMERIC(9,6), "EstadoComponente" VARCHAR(20) NOT NULL )''',
    '''CREATE TABLE "stg"."MedicoCategoriaInput" (
        "LoadBatchKey" BIGINT NOT NULL, "RowNumber" INTEGER NOT NULL, "CodigoPais" CHAR(2) NOT NULL,
        "Periodo" VARCHAR(20), "Equipo" VARCHAR(120), "LineaIdOrigen" INTEGER, "CodigoRepresentante" VARCHAR(30),
        "NombreRepresentante" VARCHAR(150), "Medico" VARCHAR(200) NOT NULL, "CentroMedico" VARCHAR(200),
        "Especialidad" VARCHAR(150), "Provincia" VARCHAR(120), "Municipio" VARCHAR(120),
        "PacientesSemana" NUMERIC(18,4), "CostoConsulta" NUMERIC(18,4), "RecetasSemana" VARCHAR(80),
        "UbicacionTerritorialCM" VARCHAR(80), "KOL" VARCHAR(150), "CategoriaExcel" VARCHAR(20),
        "Activo" BOOLEAN NOT NULL, PRIMARY KEY ("LoadBatchKey", "RowNumber") )''',
]


_FOTO = Path(__file__).with_suffix(".sql")


def upgrade():
    for s in _SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{s}"')

    # La foto viaja dentro de la imagen (`COPY . .` en el Dockerfile). Si falta,
    # se aborta: instalar un esquema a medias es peor que no instalar nada.
    if not _FOTO.is_file():
        raise RuntimeError(
            f"Falta la foto del baseline: {_FOTO}. Sin ella no se puede crear el "
            "esquema desde cero."
        )
    op.execute(_FOTO.read_text(encoding="utf-8"))

    # Las 6 tablas cat.*/stg.* sin modelo ORM (nunca estuvieron en la metadata).
    for ddl in _CAT_STG_DDL:
        op.execute(ddl)


def downgrade():
    # Basta con tumbar los esquemas en cascada: se llevan las 85 tablas de la
    # foto y las 6 de DDL explícito. No se usan los modelos, por la misma razón
    # que en upgrade().
    for s in reversed(_SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{s}" CASCADE')
    # El tipo `rol` vive en `public`, así que ningún DROP SCHEMA se lo lleva:
    # sin esto, un downgrade seguido de upgrade fallaría con "type already exists".
    op.execute("DROP TYPE IF EXISTS rol CASCADE")
