"""Baseline PostgreSQL — esquemas + tablas ORM (create_all) + star-schema cat/stg.

Edición PostgreSQL. Crea todo el esquema desde cero para Postgres:
  1. CREATE SCHEMA de los 9 esquemas.
  2. Base.metadata.create_all() → tablas ORM (Config/DW/ETL/Audit/Security/exam/Visita
     + las 13 tablas cat.* que tienen modelo ORM en cat_models.py).
  3. DDL explícito de las 6 tablas cat.*/stg.* que NO tienen modelo ORM (tipos
     PostgreSQL: VARCHAR, GENERATED BY DEFAULT AS IDENTITY, BOOLEAN, TIMESTAMPTZ,
     SMALLINT, NUMERIC).

Revision ID: 0001_baseline_postgres
Revises:
Create Date: 2026-07-04
"""
from alembic import op

revision = "0001_baseline_postgres"
down_revision = None
branch_labels = None
depends_on = None

_SCHEMAS = ["Config", "DW", "ETL", "Audit", "Security", "exam", "Visita", "cat", "stg"]

# Solo las 6 tablas cat.*/stg.* SIN modelo ORM (las otras 13 las crea create_all).
_CAT_STG_DDL = [
    '''CREATE TABLE "cat"."DimCentroMedico" (
        "CentroMedicoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CentroMedico" VARCHAR(200) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimGeografia" (
        "GeografiaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "Provincia" VARCHAR(120) NOT NULL,
        "Municipio" VARCHAR(120) NOT NULL, "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimEquipo" (
        "EquipoKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "CodigoEquipo" VARCHAR(30) NOT NULL,
        "NombreEquipo" VARCHAR(120) NOT NULL, "Descripcion" VARCHAR(250), "Activo" BOOLEAN NOT NULL )''',
    '''CREATE TABLE "cat"."DimReglaCategoriaMedica" (
        "ReglaKey" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "PaisKey" INTEGER NOT NULL, "ComponenteKey" INTEGER NOT NULL, "CodigoRegla" VARCHAR(80) NOT NULL,
        "Detalle" VARCHAR(200) NOT NULL, "ValorMinimo" NUMERIC(18,4), "ValorMaximo" NUMERIC(18,4),
        "ValorTexto" VARCHAR(200), "Criterio" SMALLINT NOT NULL, "PesoComponentePct" NUMERIC(9,6) NOT NULL,
        "PuntajePct" NUMERIC(9,6) NOT NULL, "VigenteDesde" DATE NOT NULL, "VigenteHasta" DATE,
        "Activo" BOOLEAN NOT NULL, "FechaCargaUtc" TIMESTAMPTZ NOT NULL DEFAULT now() )''',
    '''CREATE TABLE "cat"."FactMedicoCategoriaDetalle" (
        "MedicoCategoriaDetalleKey" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "MedicoCategoriaKey" BIGINT NOT NULL, "ComponenteKey" INTEGER NOT NULL, "ReglaKey" INTEGER,
        "ValorEntradaTexto" VARCHAR(200), "ValorEntradaNumero" NUMERIC(18,4), "Criterio" SMALLINT,
        "PuntajePct" NUMERIC(9,6), "EstadoComponente" VARCHAR(20) NOT NULL )''',
    '''CREATE TABLE "stg"."MedicoCategoriaInput" (
        "LoadBatchKey" BIGINT NOT NULL, "RowNumber" INTEGER NOT NULL, "CodigoPais" CHAR(2) NOT NULL,
        "Periodo" VARCHAR(20), "Equipo" VARCHAR(120), "LineaIdOrigen" INTEGER, "CodigoRepresentante" VARCHAR(30),
        "NombreRepresentante" VARCHAR(150), "Medico" VARCHAR(200) NOT NULL, "CentroMedico" VARCHAR(200),
        "Especialidad" VARCHAR(150), "Provincia" VARCHAR(120), "Municipio" VARCHAR(120),
        "PacientesSemana" NUMERIC(18,4), "CostoConsulta" NUMERIC(18,4), "RecetasSemana" VARCHAR(80),
        "UbicacionTerritorialCM" VARCHAR(80), "KOL" VARCHAR(150), "CategoriaExcel" VARCHAR(20),
        "Activo" BOOLEAN NOT NULL, PRIMARY KEY ("LoadBatchKey", "RowNumber") )''',
]


def upgrade():
    bind = op.get_bind()
    for s in _SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{s}"')
    # Tablas ORM (incluye las 13 tablas cat.* de cat_models) desde los modelos.
    import app.models.usuario  # noqa: F401
    import app.models.dimensiones  # noqa: F401
    import app.models.hechos  # noqa: F401
    import app.models.visita  # noqa: F401
    import app.models.exam_models  # noqa: F401
    import app.models.cat_models  # noqa: F401
    from app.db.database import Base
    Base.metadata.create_all(bind=bind)
    # Las 6 tablas cat.*/stg.* sin modelo ORM.
    for ddl in _CAT_STG_DDL:
        op.execute(ddl)


def downgrade():
    import re
    for ddl in _CAT_STG_DDL:
        m = re.search(r'CREATE TABLE (".+?"\.".+?")', ddl)
        if m:
            op.execute(f'DROP TABLE IF EXISTS {m.group(1)} CASCADE')
    import app.models.usuario, app.models.dimensiones, app.models.hechos  # noqa: F401
    import app.models.visita, app.models.exam_models, app.models.cat_models  # noqa: F401
    from app.db.database import Base
    Base.metadata.drop_all(bind=op.get_bind())
    for s in reversed(_SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{s}" CASCADE')
