"""baseline - punto de partida del versionado (no-op)

Esta migracion NO ejecuta cambios de esquema. Las tablas ya existian en la
base de datos antes de adoptar Alembic; esta revision solo marca el punto
desde el cual empezamos a versionar los cambios de aqui en adelante.

Se aplica con `alembic stamp head` (NO con `upgrade`), para decirle a Alembic
"la BD ya esta en este estado" sin intentar recrear tablas existentes.

El script auto-generado original (que intentaba recrear TODAS las tablas
porque no existia `alembic_version`) fue descartado a proposito: aplicarlo
habria fallado por tablas duplicadas y no habria corregido el drift real
(columna `pais_id` faltante en Config.DIM_Indicador). Ese fix vive en la
siguiente revision.

Revision ID: fb61c3c89ec7
Revises:
Create Date: 2026-06-06 03:42:40.041209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb61c3c89ec7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline no-op: las tablas ya existen, esta revision solo se 'stampea'."""
    pass


def _ORIGINAL_AUTOGEN_DO_NOT_USE_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FACT_Auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('tabla', sa.String(length=100), nullable=True),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='Audit'
    )
    op.create_index(op.f('ix_Audit_FACT_Auditoria_fecha_hora'), 'FACT_Auditoria', ['fecha_hora'], unique=False, schema='Audit')
    op.create_table('DIM_Capacitacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('duracion_horas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('puntaje_aprobacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='Config'
    )
    op.create_table('DIM_Mes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('abrev', sa.String(length=5), nullable=True),
    sa.Column('ciclo_mes', sa.Integer(), nullable=True),
    sa.Column('trimestre', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('DIM_Pais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('zona_horaria', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='Config'
    )
    op.create_table('DIM_Premio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='Config'
    )
    op.create_table('FACT_CargaExcel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('tipo_archivo', sa.String(length=50), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total_filas', sa.Integer(), nullable=False),
    sa.Column('filas_exitosas', sa.Integer(), nullable=False),
    sa.Column('filas_error', sa.Integer(), nullable=False),
    sa.Column('filas_advertencia', sa.Integer(), nullable=False),
    sa.Column('log_errores', sa.Text(), nullable=True),
    sa.Column('log_advertencias', sa.Text(), nullable=True),
    sa.Column('duracion_segundos', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ETL'
    )
    op.create_table('DIM_Ciclo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nombre_canonico', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_laborables', sa.Integer(), nullable=False),
    sa.Column('cerrado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('DIM_Indicador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('tipo_periodo', sa.String(length=10), nullable=False),
    sa.Column('ponderacion_pct', sa.Integer(), nullable=False),
    sa.Column('escala', sa.Integer(), nullable=False),
    sa.Column('valor_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valor_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('peso_iup', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('meta_global', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('DIM_Linea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('FACT_Reconocimiento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('rm_id', sa.Integer(), nullable=True),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.Column('premio_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('iup_al_momento', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('posicion_ranking', sa.Integer(), nullable=True),
    sa.Column('certificado_generado', sa.Boolean(), nullable=False),
    sa.Column('certificado_url', sa.String(length=500), nullable=True),
    sa.Column('aprobado_por', sa.String(length=200), nullable=True),
    sa.Column('fecha_reconocimiento', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['premio_id'], ['Config.DIM_Premio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_Reconocimiento_pais_id'), 'FACT_Reconocimiento', ['pais_id'], unique=False, schema='DW')
    op.create_table('DIM_Usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'PRESIDENCIA', 'DIR_COMERCIAL', 'GERENTE_PRODUCTIVIDAD', 'GERENTE_DISTRITO', 'GERENTE_MARCA', 'REPRESENTANTE_MEDICO', 'CONSULTA', name='rol'), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('rm_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='Security'
    )
    op.create_index(op.f('ix_Security_DIM_Usuario_username'), 'DIM_Usuario', ['username'], unique=True, schema='Security')
    op.create_table('DIM_Gerente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['linea_id'], ['Config.DIM_Linea.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='Config'
    )
    op.create_table('DIM_IndicadorTabla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('rango_desde', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rango_hasta', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('puntos', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['Config.DIM_Indicador.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('DIM_ReglaElegibilidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('indicador_codigo', sa.String(length=50), nullable=False),
    sa.Column('umbral_minimo', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('aplica_ranking', sa.Boolean(), nullable=False),
    sa.Column('aplica_reconocimiento', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='Config'
    )
    op.create_table('DIM_RM',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['gerente_id'], ['Config.DIM_Gerente.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['Config.DIM_Linea.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    schema='Config'
    )
    op.create_table('FACT_Capacitacion',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('horas_completadas', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fecha_actividad', sa.Date(), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capacitacion_id'], ['Config.DIM_Capacitacion.id'], ),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_Capacitacion_ciclo_id'), 'FACT_Capacitacion', ['ciclo_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Capacitacion_pais_id'), 'FACT_Capacitacion', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Capacitacion_rm_id'), 'FACT_Capacitacion', ['rm_id'], unique=False, schema='DW')
    op.create_table('FACT_Coaching',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('gerente_id', sa.Integer(), nullable=False),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('coaching_programado', sa.Integer(), nullable=False),
    sa.Column('coaching_ejecutado', sa.Integer(), nullable=False),
    sa.Column('cumplimiento_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('calificacion_calidad', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('peso_cantidad', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('peso_calidad', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('resultado_coaching', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_coaching', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['gerente_id'], ['Config.DIM_Gerente.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_Coaching_ciclo_id'), 'FACT_Coaching', ['ciclo_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Coaching_pais_id'), 'FACT_Coaching', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Coaching_rm_id'), 'FACT_Coaching', ['rm_id'], unique=False, schema='DW')
    op.create_table('FACT_EVOIR',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('producto_codigo', sa.String(length=50), nullable=False),
    sa.Column('producto_nombre', sa.String(length=200), nullable=False),
    sa.Column('prescripciones_actuales', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('prescripciones_anteriores', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('evolucion_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_EVOIR_ciclo_id'), 'FACT_EVOIR', ['ciclo_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_EVOIR_pais_id'), 'FACT_EVOIR', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_EVOIR_rm_id'), 'FACT_EVOIR', ['rm_id'], unique=False, schema='DW')
    op.create_table('FACT_Ranking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=True),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=True),
    sa.Column('mes_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ranking', sa.String(length=30), nullable=False),
    sa.Column('iup_total', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('iup_productividad', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('iup_comercial', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('iup_coaching', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('iup_capacitacion', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('iup_consistencia', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('posicion_anterior', sa.Integer(), nullable=True),
    sa.Column('elegible', sa.Boolean(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_Ranking_pais_id'), 'FACT_Ranking', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Ranking_rm_id'), 'FACT_Ranking', ['rm_id'], unique=False, schema='DW')
    op.create_table('FACT_RendimientoComercial',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('gerente_id', sa.Integer(), nullable=True),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('mes_id', sa.Integer(), nullable=True),
    sa.Column('valor_real', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valor_meta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('porcentaje_cumplimiento', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('carga_excel_id', sa.Integer(), nullable=True),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['indicador_id'], ['Config.DIM_Indicador.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['Config.DIM_Linea.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_RendimientoComercial_ciclo_id'), 'FACT_RendimientoComercial', ['ciclo_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_RendimientoComercial_fecha_carga'), 'FACT_RendimientoComercial', ['fecha_carga'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_RendimientoComercial_indicador_id'), 'FACT_RendimientoComercial', ['indicador_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_RendimientoComercial_pais_id'), 'FACT_RendimientoComercial', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_RendimientoComercial_rm_id'), 'FACT_RendimientoComercial', ['rm_id'], unique=False, schema='DW')
    op.create_table('FACT_Ventas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('rm_id', sa.Integer(), nullable=False),
    sa.Column('ciclo_id', sa.Integer(), nullable=False),
    sa.Column('ventas_reales', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cuota', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('cumplimiento_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('crecimiento_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ciclo_id'], ['Config.DIM_Ciclo.id'], ),
    sa.ForeignKeyConstraint(['linea_id'], ['Config.DIM_Linea.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['Config.DIM_Pais.id'], ),
    sa.ForeignKeyConstraint(['rm_id'], ['Config.DIM_RM.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='DW'
    )
    op.create_index(op.f('ix_DW_FACT_Ventas_ciclo_id'), 'FACT_Ventas', ['ciclo_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Ventas_pais_id'), 'FACT_Ventas', ['pais_id'], unique=False, schema='DW')
    op.create_index(op.f('ix_DW_FACT_Ventas_rm_id'), 'FACT_Ventas', ['rm_id'], unique=False, schema='DW')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Baseline no-op: nada que revertir (no creamos nada en upgrade)."""
    pass


def _ORIGINAL_AUTOGEN_DO_NOT_USE_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DW_FACT_Ventas_rm_id'), table_name='FACT_Ventas', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Ventas_pais_id'), table_name='FACT_Ventas', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Ventas_ciclo_id'), table_name='FACT_Ventas', schema='DW')
    op.drop_table('FACT_Ventas', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_RendimientoComercial_rm_id'), table_name='FACT_RendimientoComercial', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_RendimientoComercial_pais_id'), table_name='FACT_RendimientoComercial', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_RendimientoComercial_indicador_id'), table_name='FACT_RendimientoComercial', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_RendimientoComercial_fecha_carga'), table_name='FACT_RendimientoComercial', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_RendimientoComercial_ciclo_id'), table_name='FACT_RendimientoComercial', schema='DW')
    op.drop_table('FACT_RendimientoComercial', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Ranking_rm_id'), table_name='FACT_Ranking', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Ranking_pais_id'), table_name='FACT_Ranking', schema='DW')
    op.drop_table('FACT_Ranking', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_EVOIR_rm_id'), table_name='FACT_EVOIR', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_EVOIR_pais_id'), table_name='FACT_EVOIR', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_EVOIR_ciclo_id'), table_name='FACT_EVOIR', schema='DW')
    op.drop_table('FACT_EVOIR', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Coaching_rm_id'), table_name='FACT_Coaching', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Coaching_pais_id'), table_name='FACT_Coaching', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Coaching_ciclo_id'), table_name='FACT_Coaching', schema='DW')
    op.drop_table('FACT_Coaching', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Capacitacion_rm_id'), table_name='FACT_Capacitacion', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Capacitacion_pais_id'), table_name='FACT_Capacitacion', schema='DW')
    op.drop_index(op.f('ix_DW_FACT_Capacitacion_ciclo_id'), table_name='FACT_Capacitacion', schema='DW')
    op.drop_table('FACT_Capacitacion', schema='DW')
    op.drop_table('DIM_RM', schema='Config')
    op.drop_table('DIM_ReglaElegibilidad', schema='Config')
    op.drop_table('DIM_IndicadorTabla', schema='Config')
    op.drop_table('DIM_Gerente', schema='Config')
    op.drop_index(op.f('ix_Security_DIM_Usuario_username'), table_name='DIM_Usuario', schema='Security')
    op.drop_table('DIM_Usuario', schema='Security')
    op.drop_index(op.f('ix_DW_FACT_Reconocimiento_pais_id'), table_name='FACT_Reconocimiento', schema='DW')
    op.drop_table('FACT_Reconocimiento', schema='DW')
    op.drop_table('DIM_Linea', schema='Config')
    op.drop_table('DIM_Indicador', schema='Config')
    op.drop_table('DIM_Ciclo', schema='Config')
    op.drop_table('FACT_CargaExcel', schema='ETL')
    op.drop_table('DIM_Premio', schema='Config')
    op.drop_table('DIM_Pais', schema='Config')
    op.drop_table('DIM_Mes', schema='Config')
    op.drop_table('DIM_Capacitacion', schema='Config')
    op.drop_index(op.f('ix_Audit_FACT_Auditoria_fecha_hora'), table_name='FACT_Auditoria', schema='Audit')
    op.drop_table('FACT_Auditoria', schema='Audit')
    # ### end Alembic commands ###
